### ISSUE TITLE
Auth Assertion Header missing for ordersCreate function

### ISSUE THREAD

**Issue by MichaelDurfey** [paypal/PayPal-TypeScript-Server-SDK#11]
Hello,

Passing a 'PAYPAL-AUTH-ASSERTION' header along with the 'PAYPAL-PARTNER-ATTRIBUTION-ID' is necessary for creating an order via multiparty integration. 

There is ability to [pass in authAssertionHeader for orderTrackCreate](https://github.com/paypal/PayPal-TypeScript-Server-SDK/blob/main/doc/controllers/orders.md#orders-track-create), but this is necessary also for `orderCreate` to create the order so that the partner can affiliate the transaction to the seller. 
It should be passed along with the PayPal-Partner-Attribution-Id as shown here: https://developer.paypal.com/docs/multiparty/checkout/advanced/processing/#link-createorderrequest.

Thanks!

**Comment by LeonarthusMectus** [comment]
Hey @MichaelDurfey 

Thanks for the report!  This certainly appears to be a missing header.  I'm working with a few other teams now to confirm what endpoints this header applies to, so we can ideally update them all to accept it in one pass.  I'll leave this open and follow up when we have a fix incoming.

**Comment by LeonarthusMectus** [comment]
Hey @MichaelDurfey 

Just giving you a heads up that 0.6.1 is out and should include the auth assertion headers for both Orders & Payments methods where they were previously missing.  It took a big of wrangling with the API teams to have them hammer this out, but take a look and let us know if you notice anything else missing.
